messaging/urls.py
from django.conf.urls import *
from . import views


app_name = 'messaging'
urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.UserDetailView.as_view(), name='user_detail'),
    url(r'^(?P<user_id>[0-9]+)/conversation/$', views.convo, name='convo_view'),
    url(r'^results/$', views.search, name='results'),
    url(r'^$', views.UserIndexView.as_view(), name='user_list')
    
]

skIM/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from skIM import settings
admin.autodiscover()

urlpatterns = [
    url(r'^messaging/', include('registration.backends.default.urls')),
    url(r'^messaging/', include('messaging.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

messaging/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
#username, (encrypts) password, email, first_name, last_name, date_joined, last_login
    
class Conversation(models.Model):
    users = models.ManyToManyField(User)
    
class Message(models.Model):
    body = models.CharField(max_length=1000)
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
    sent_date = models.DateField()

messaging/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['body',]

messaging/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from .models import *
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import Context
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from .forms import MessageForm


class UserDetailView(generic.DetailView):
    model = User
    template_name = 'messaging/detail.html'


def convo(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    curr_user = request.user

    # Will eventually support group conversations, for now we'll just get the one
    conversation = user.conversation_set.get(pk__in=curr_user.conversation_set.all())
    form = MessageForm()
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sent_date = timezone.now()
            message.conversation_id = conversation.id
            message.save()
    return render(request, 'conversations/detail.html', {'form': form, 'user': user_id,
      'conversation': conversation})  



class UserIndexView(LoginRequiredMixin, generic.ListView):
    login_url = '/messaging/login/'
    redirect_field_name = 'redirect_to'
    model = User
    template_name = 'messaging/list.html'
    context_object_name = 'users'


def search(request):
    query = request.GET.get('query')
    qset = Q()
    if query:
        qset |= Q(username__contains=query)
    results = User.objects.filter(qset)
    return render(request, 'messaging/results.html', {'results': results, 'query': query})

messaging/templates/base.html
<head>
<title></title>
</head>
<body>
{% block content %}{% endblock %}
</body>

messaging/templates/conversations/detail.html
{% extends 'inner_base.html' %}
{% block content %}
{% for message in conversation.message_set.all %}
</br>
{{message.sent_date}}<br/>
{{message.body}}</br>
-----------------------------------------</br>
{% endfor %}


{# honeypot for spambots #}
<form hidden='true'>
<input type='text' name=''>
<input type='submit' value='' />
</form>

<form action='.' method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Save</button>
</form>
{% endblock %}

messaging/templates/inner_base.html
{# So inner pages look different than authentication ones #}
<head>
<title></title>
{% load staticfiles %}
<script src="{% static "js/jquery-1.11.1.js" %}"></script>
<script src="{% static "js/rango-jquery.js" %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link rel="script" type="js" href="{% static 'functions.js' %}" >
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />

</head>

<!-- TODO Basic design! -->
<nav>
<ul>
<li><a href='{% url "messaging:results" %}' class='button'>See All Users</a></li>
<li><a href='/messaging/logout/' class='button'>Logout</a></li>
<li><form method='GET' action='{% url "messaging:results" %}' style='display:inline;'>
      <input type='text' name='query' />
      <input type='submit' />
</form></li>
</ul>

<select id='drop'>
<option value='{% url "messaging:results" %}' class='button'>See All Users</option>
<option value='/messaging/logout/' class='button'>Logout</option>
<option id='search' value='Search'>Search</option>
<form id='search_field' method='GET' action='{% url "messaging:results" %}' style='display:inline;'>
      <input type='text' name='query' />
      <input type='submit' />
</form>
</select>
</nav>
{% block content %}{% endblock %}

</body>

messaging/templates/messaging/detail.html
{% extends 'inner_base.html' %}
{% block content %}
<h1>{{user.username}}</h1> <br/>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<h2>{{user.first_name}} {{user.last_name}}</h2> <br/>
<a href='{% url "messaging:convo_view" user.id %}'>See our conversation</a></br>
</br>
{% endblock %}

messaging/templates/messaging/list.html
{% extends 'inner_base.html' %}
{% block content %}
All users </br>
{% for u in users %}
  <a href='{% url "messaging:user_detail" u.id %}'>{{ u.username }}</a></br>
{% endfor %}
{% endblock %}

messaging/templates/messaging/results.html
{% extends 'inner_base.html' %}
{% block content %}
Users that match {% if query %}{{ query }}{% else %}{{'anything'}}{% endif %}</br>
{% for u in results %}
<a href='{% url "messaging:user_detail" u.id %}'>{{ u.username }}</a></br>
{% endfor %}
{% endblock %}